[package]
name = "gongbotrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.2.8", features = ["postgres"] }
diesel-async = { version = "0.5.2", features = ["postgres"] }
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
