[package]
name = "gongbotrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.40"
chrono-tz = "0.10.3"
diesel = { version = "2.2.8", features = ["postgres", "chrono"] }
diesel-async = { version = "0.5.2", features = ["bb8", "postgres"] }
diesel-derive-enum = "2.1.0"
dotenvy = "0.15.7"
enum_stringify = "0.6.3"
envconfig = "0.11.0"
serde = { version = "1.0.219", features = ["derive", "serde_derive"] }
teloxide = { version = "0.14.0", features = ["macros", "postgres-storage-nativetls"] }
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros"] }
