name: Build && Deploy
on: [push]

jobs:
  test:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - name: Restore cached toolchain 
        id: cache-toolchain
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ runner.os }}-rust-toolchain
      - name: Install minimal stable with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Save cached toolchain 
        id: cache-toolchain
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ steps.cache-toolchain.outputs.cache-primary-key }}
      - uses: actions/checkout@v4
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Upload Release Binary
        uses: actions/upload-artifact@v3
        with:
          name: botrunner
          path: target/x86_64-unknown-linux-gnu/release/gongbotrs
