name: Build && Deploy
on: [push]

jobs:
  test:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2

      - uses: actions/checkout@v4

      - name: Restore cached cargo dependencies
        id: cache-toolchain
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.rustup
            ~/.cargo
          key: ${{ runner.os }}-rust-toolchain
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: Save cached cargo dependencies
        id: cache-toolchain
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.rustup/toolchains
          key: ${{ steps.cache-toolchain.outputs.cache-primary-key }}

      - name: Upload Release Binary
        uses: actions/upload-artifact@v3
        with:
          name: botrunner
          path: target/x86_64-unknown-linux-gnu/release/gongbotrs
