name: Build && Deploy
on: [push]

jobs:
  test:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v4
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - run: |
          ls target
          ls target/*
          ls target/*/release
      - name: Upload Release Binary
        uses: actions/upload-artifact@v3
        with:
          name: botrunner
          path: target/x86_64-unknown-linux-gnu/release/gongbot
