// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::prelude::*;
#[derive(Queryable, Debug)]
#[diesel(table_name = users)]
pub struct User {
    pub id: i64,
    pub is_admin: bool,
}
